### ISSUE TITLE
Phylogenetic Tree

### ISSUE THREAD

**Issue by cazzlewazzle89** [BenBeresfordJones/MGBC#24]
Hi @BenBeresfordJones,

Love the resource and looking forward to using it for metagenome mapping.
I want to compute phylogeny-aware diversity metrics and I'm wondering if you have a pre-computed phylogenetic tree with all the genomes in `mgbc-hqnr_26640` that you could share?
It would save me having to make one myself.

Thanks,
Calum

**Comment by BenBeresfordJones** [comment]
Hi Calum, 

Glad to hear you like the resource!

I am afraid that I have not generated a phylogeny containing all 26,640 genomes. Sorry I cannot be of more help.

Best wishes,
Ben

**Comment by cazzlewazzle89** [comment]
Thanks for the reply Ben.
No worries. I'll share when I generate one.

**Comment by BenBeresfordJones** [comment]
HI Calum,

Apologies for the back and forth but I had a better dig around and turns out I had actually generated a tree - dendrogram:
[nrhq_26640.dnd.txt](https://github.com/BenBeresfordJones/MGBC/files/9035786/nrhq_26640.dnd.txt). 
This tree was generated using FastTree (v2.1.10) and the alignment from gtdbtk (v1.3) bac120. Hope this helps!

**Comment by cazzlewazzle89** [comment]
Thanks Ben. Saves me the effort. I was about to use the exact same method 😅
